export interface WebviewMessage {
  type:
    | "syncRemoteInfo"
    | "createRouterAndPageTemplate"
    | "openAntAiEditor"
    | "syncLatestCode"
    | "checkForDebugging"
    | "syncRemoteInfo"
    | "openBrowser"
    | "copyCodeToProject"
    | "startLocalDevelopmentAndPreview"
    | "hideWelcomeCard"
    | "getState"
    | "setState"
    | "openReadme"
    | "login"
    | "loginSuccess"
    | "loginFailed"
    | "logout"
    | "checkAuth"
    | "showLogin"
    | "openSettings"
    | "openProfile"
    | "openChat"
    | "updateUserInfo"
    | "openCodeSnap"
    | "saveCodeSnap"
    | "deleteCodeSnap"
    | "openTodo"
    | "addTodo"
    | "updateTodo"
    | "deleteTodo"
    | "completeTodo"
    | "openDebugMD"
    | "importMDForDebug"
    | "openMcpService"
    | "createMcpService"
    | "openExistingMcpService"
    | "deleteMcpService"
    | "testMcpService"
    | "openMcpServiceDirectory"
    | "copyToClipboard"
    | "openProjectScaffold"
    | "createProject"
    | "sendChatMessage"
    | "chatResponse"
    | "getOllamaModels"
    | "ollamaModels"
    | "seoDiagnosis"
    | "seoDiagnosisResult"
    | "seoDiagnosisProgress"
    | "openSeoAnalyzer";
  data?: any;
  key?: string;
  value?: any;
}

export const WebviewMessageType = {
  syncRemoteInfo: "syncRemoteInfo",
  createRouterAndPageTemplate: "createRouterAndPageTemplate",
  openAntAiEditor: "openAntAiEditor",
  syncLatestCode: "syncLatestCode",
  checkForDebugging: "checkForDebugging",
  openBrowser: "openBrowser",
  copyCodeToProject: "copyCodeToProject",
  startLocalDevelopmentAndPreview: "startLocalDevelopmentAndPreview",
  hideWelcomeCard: "hideWelcomeCard",
  getState: "getState",
  setState: "setState",
  openReadme: "openReadme",
  login: "login",
  loginSuccess: "loginSuccess",
  loginFailed: "loginFailed",
  logout: "logout",
  checkAuth: "checkAuth",
  showLogin: "showLogin",
  openSettings: "openSettings",
  openProfile: "openProfile",
  openChat: "openChat",
  updateUserInfo: "updateUserInfo",
  openCodeSnap: "openCodeSnap",
  saveCodeSnap: "saveCodeSnap",
  deleteCodeSnap: "deleteCodeSnap",
  openTodo: "openTodo",
  addTodo: "addTodo",
  updateTodo: "updateTodo",
  deleteTodo: "deleteTodo",
  completeTodo: "completeTodo",
  openDebugMD: "openDebugMD",
  importMDForDebug: "importMDForDebug",
  openMcpService: "openMcpService",
  createMcpService: "createMcpService",
  openExistingMcpService: "openExistingMcpService",
  deleteMcpService: "deleteMcpService",
  testMcpService: "testMcpService",
  openMcpServiceDirectory: "openMcpServiceDirectory",
  copyToClipboard: "copyToClipboard",
  openProjectScaffold: "openProjectScaffold",
  createProject: "createProject",
  sendChatMessage: "sendChatMessage",
  chatResponse: "chatResponse",
  getOllamaModels: "getOllamaModels",
  ollamaModels: "ollamaModels",
  seoDiagnosis: "seoDiagnosis",
  seoDiagnosisResult: "seoDiagnosisResult",
  seoDiagnosisProgress: "seoDiagnosisProgress",
  openSeoAnalyzer: "openSeoAnalyzer",
};
